apiVersion: v1
kind: Secret
metadata:
  name: pullsecret-cluster-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  '.dockerconfigjson': {{ .Values.pullSecret }}
type: kubernetes.io/dockerconfigjson